/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QQ_H_RPCGEN
#define _QQ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define QQ 0x30000003
#define VQQ 11

#if defined(__STDC__) || defined(__cplusplus)
#define f 1
extern  double * f_11(int , CLIENT *);
extern  double * f_11_svc(int , struct svc_req *);
extern int qq_11_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define f 1
extern  double * f_11();
extern  double * f_11_svc();
extern int qq_11_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QQ_H_RPCGEN */
