/*	Archivo:	qq_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "qq.h"

double *
f_11_svc(int arg1,  struct svc_req *rqstp)
{
	static double  result;
	/* agregado v */
	result = arg1 + (1.0 * arg1)/100;
	/* agregado ^ */
	return &result;
}
/*	Fin del archivo:	qq_server.c */
